### PR TITLE
Draft: Fixes for the windows VS2022 cmake build

### LINKED ISSUE #210: Windows: Visual Studio 2022 CMake build is broken
When building the latest with VS2022 using the CMake instructions the build fails on the protobuf build.  Found by @anniegsmith

### PR DESCRIPTION
**Pull request by JBBee**
Closes #210

### CODE REVIEW

File: src/api/cpp/GravityConfigParser.cpp [hunk 1]
```diff
@@ -26,6 +26,9 @@
 #include <map>
 #include <iostream>
 
+#ifdef min
```
Comment (mbarger99) [inline src/api/cpp/GravityConfigParser.cpp:29]: If these lines no longer have any value, please delete them.  If there's a decent chance they might be needed again, can you add a comment explaining why?

Comment (mbarger99) [reply src/api/cpp/GravityConfigParser.cpp:29]: Nevermind, misread what this was doing
